version: '3.8'

services:
  app:
    image: anime_scrapy:1.0.1-test
    container_name: anime_scrapy
    depends_on:
      - database
    environment:
      - USERNAME=anime_scrapy
      - PASSWORD=anime_scrapy_password
      - HOST=database
      - PORT=3306
      - PICTURE_PATH=/app/pictures
    volumes:
      - ./picture:/app/pictures
    restart: unless-stopped

  database:
    image: mariadb:11.8.3-noble
    container_name: database
    environment:
      - MARIADB_ROOT_PASSWORD=MARIADB_DOCKER_PASSWORD
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/logs:/var/log/mysql
      - ./database/create.sql:/docker-entrypoint-initdb.d/01-create.sql
      - ./database/user.sql:/docker-entrypoint-initdb.d/02-user.sql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped

